const $=id=>document.getElementById(id);let SITE=null,heroItems=[],heroIndex=0,heroTimer=null;
function jsonp(action,extra={}){return new Promise((resolve,reject)=>{const cb='__vigy_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const q=new URLSearchParams({action,callback:cb,...extra});window[cb]=d=>{cleanup();d&&d.ok?resolve(d):reject(new Error(d&&d.error||'API error'))};s.onerror=()=>{cleanup();reject(new Error('Apps Script API did not respond.'))};s.src=API_URL+'?'+q.toString();document.body.appendChild(s);function cleanup(){delete window[cb];s.remove()}})}
function mediaUrl(x){
  const raw=String(x?.ImageURL||x?.url||'').trim();
  const id=String(x?.DriveFileId||'').trim();
  const fromId=id?`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w2000`:'';
  if(!raw) return fromId;
  if(/^https?:\/\/drive\.google\.com\/file\/d\//i.test(raw)){
    const m=raw.match(/\/file\/d\/([^/]+)/i); return m?`https://drive.google.com/thumbnail?id=${encodeURIComponent(m[1])}&sz=w2000`:raw;
  }
  const q=raw.match(/[?&]id=([^&]+)/i);
  if(/drive\.google\.com/i.test(raw)&&q) return `https://drive.google.com/thumbnail?id=${encodeURIComponent(q[1])}&sz=w2000`;
  return raw;
}
function setMediaSrc(el,x){
  if(!el)return;
  const primary=mediaUrl(x);
  el.src=primary;
  if(primary && x?.DriveFileId){
    el.onerror=()=>{el.onerror=null;el.src=`https://drive.google.com/uc?export=view&id=${encodeURIComponent(x.DriveFileId)}`};
  }
}
function getSetting(k){return(SITE.settings||[]).find(x=>String(x.Key)===k)?.Value||''}function setText(id,v){const e=$(id);if(e)e.textContent=v||''}function setAttr(id,a,v){const e=$(id);if(e&&v!=null)e.setAttribute(a,v)}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(d){SITE=d;const s=getSetting;setText('brandName',s('siteName'));setText('brandTagline',s('siteTagline'));setText('footerName',s('siteName'));setText('footerTagline',s('siteTagline'));setText('footerText',s('footerText'));const logo=s('logoUrl');['logo','footerLogo'].forEach(id=>{const e=$(id);if(e&&logo){e.src=mediaUrl({ImageURL:logo});e.onerror=()=>{e.onerror=null;e.src=logo};e.style.display='block'}});['heroEyebrow','heroTitle','heroText','heroButton','aboutEyebrow','aboutTitle','aboutText','aboutButton','servicesEyebrow','servicesTitle','servicesText','plansEyebrow','plansTitle','plansText','galleryEyebrow','galleryTitle','galleryText','contactEyebrow','contactTitle','contactText','whyTitle','why1Title','why1Text','why2Title','why2Text','why3Title','why3Text','why4Title','why4Text'].forEach(id=>setText(id,s(id)));setAttr('heroButton','href',s('heroButtonLink')||'#contact');setAttr('aboutButton','href',s('aboutButtonLink')||'#about');setText('headerCta',s('headerCta')||'Get Started');setAttr('headerCta','href',s('headerCtaLink')||'#contact');[['navHome','navHome','#home'],['navAbout','navAbout','#about'],['navServices','navServices','#services'],['navPlans','navPlans','#plans'],['navGallery','navGallery','#gallery'],['navContact','navContact','#contact']].forEach(([id,k,href])=>{setText(id,s(k)||id);setAttr(id,'href',href)});const phone=s('phone'),wa=s('whatsapp'),email=s('email');setText('phoneLink',phone);setAttr('phoneLink','href','tel:'+phone.replace(/\s/g,''));setText('whatsappLink',wa);setAttr('whatsappLink','href','https://wa.me/'+wa.replace(/\D/g,''));setText('emailLink',email);setAttr('emailLink','href','mailto:'+email);setText('addressText',s('address'));[['instagram','instagram'],['facebook','facebook'],['youtube','youtube'],['linkedin','linkedin']].forEach(([id,k])=>setAttr(id,'href',s(k)||'#'));setAttr('mapLink','href',s('mapLink')||'#');const mf=$('mapFrame');if(s('mapEmbedUrl')){mf.src=s('mapEmbedUrl');mf.style.display='block'}else mf.style.display='none';
$('quickGrid').innerHTML=(d.services||[]).slice(0,8).map(x=>`<div class="quick-card"><div class="quick-icon">${esc(x.Icon||'✦')}</div><strong>${esc(x.Title)}</strong><small>${esc(x.Short)}</small></div>`).join('');$('servicesGrid').innerHTML=(d.services||[]).map(x=>`<article class="service-card"><div class="service-icon">${esc(x.Icon||'✦')}</div><h3>${esc(x.Title)}</h3><p>${esc(x.Description||x.Short)}</p><span class="mini">${esc(x.Short||'Explore service')} →</span></article>`).join('');$('plansGrid').innerHTML=(d.plans||[]).map((x,i)=>`<article class="plan-card ${String(x.Badge||'').toLowerCase().includes('popular')?'featured':''}">${x.Badge?`<span class="badge">${esc(x.Badge)}</span>`:''}<h3>${esc(x.Name)}</h3><div class="price">${esc(x.Price)}</div><div class="billing">${esc(x.Billing)}</div><ul class="features">${String(x.Features||'').split('|').filter(Boolean).map(f=>`<li>${esc(f.trim())}</li>`).join('')}</ul><a class="btn ${i===1?'btn-gold':'btn-dark'}" href="#contact">${esc(x.CTA||'Get Started')} <span>→</span></a></article>`).join('');
const gal=(d.gallery||[]);$('galleryGrid').innerHTML=gal.filter(x=>String(x.Section||'Gallery').toLowerCase()!=='hero slider').map(x=>{const v=String(x.MediaType||'image').toLowerCase()==='video';return `<button class="gallery-card media-card" onclick="openMediaById('${esc(x.ID)}')">${v?`<video src="${esc(mediaUrl(x))}" muted playsinline preload="metadata"></video><span class="play-badge">▶</span>`:`<img src="${esc(mediaUrl(x))}" alt="${esc(x.Title)}" loading="lazy" onerror="this.onerror=null;this.src='${esc(x.DriveFileId?`https://drive.google.com/uc?export=view&id=${x.DriveFileId}`:x.ImageURL)}'">`}<div class="gallery-meta"><strong>${esc(x.Title)}</strong><span>${esc(x.Category)}</span></div></button>`}).join('');$('testimonialsGrid').innerHTML=(d.testimonials||[]).map(x=>`<article class="testimonial"><div class="stars">${'★'.repeat(Math.max(0,Math.min(5,Number(x.Rating||5))))}</div><p>“${esc(x.Quote)}”</p><strong>${esc(x.Name)}</strong><small>${esc(x.Role)}</small></article>`).join('');setupHero(gal.filter(x=>String(x.Section||'').toLowerCase()==='hero slider'&&String(x.MediaType||'image').toLowerCase()==='image').slice(0,10));document.title=(s('siteName')||'Vigyapan')+' — '+(s('siteTagline')||'Where Brands Get Noticed');$('loader').classList.add('hide')}
function setupHero(items){heroItems=items.length?items:(getSetting('heroImage')?[{ImageURL:getSetting('heroImage'),Title:'Hero'}]:[]);heroIndex=0;clearInterval(heroTimer);renderHero();const ms=Math.max(2500,Number(getSetting('heroAutoMs')||4500));if(heroItems.length>1)heroTimer=setInterval(()=>heroMove(1),ms)}function renderHero(){const wrap=$('heroSlider'),dots=$('heroDots');wrap.innerHTML=heroItems.map((x,i)=>`<img class="hero-slide ${i===heroIndex?'active':''}" src="${esc(mediaUrl(x))}" alt="${esc(x.Title)}" onerror="this.onerror=null;this.src='${esc(x.DriveFileId?`https://drive.google.com/uc?export=view&id=${x.DriveFileId}`:x.ImageURL)}'">`).join('');dots.innerHTML=heroItems.map((x,i)=>`<button class="dot ${i===heroIndex?'active':''}" onclick="heroGo(${i})"></button>`).join('');$('heroDots').style.display=heroItems.length>1?'flex':'none';document.querySelectorAll('.slide-arrow').forEach(e=>e.style.display=heroItems.length>1?'block':'none')}
function heroGo(i){if(!heroItems.length)return;heroIndex=(i+heroItems.length)%heroItems.length;renderHero()}function heroMove(n){heroGo(heroIndex+n)}
function openMediaById(id){const x=(SITE.gallery||[]).find(r=>String(r.ID)===String(id));if(x)openMedia(x)}
function openMedia(x){const m=$('mediaModal'),v=$('mediaViewer');m.classList.add('show');const video=String(x.MediaType||'image').toLowerCase()==='video';v.innerHTML=video?`<video id="activeMedia" src="${esc(mediaUrl(x))}" controls autoplay playsinline></video>`:`<img id="activeMedia" src="${esc(mediaUrl(x))}" alt="${esc(x.Title)}" onerror="this.onerror=null;this.src='${esc(x.DriveFileId?`https://drive.google.com/uc?export=view&id=${x.DriveFileId}`:x.ImageURL)}'">`;document.body.classList.add('modal-open')}
function closeMedia(e){if(e&&e.target&&e.target.id!=='mediaModal'&&!e.target.classList.contains('media-close'))return;$('mediaModal').classList.remove('show');$('mediaViewer').innerHTML='';document.body.classList.remove('modal-open')}
function mediaFullscreen(e){e.stopPropagation();const el=$('activeMedia');if(el?.requestFullscreen)el.requestFullscreen()}
function init(){if(location.hash.toLowerCase()==='#admin'){location.href=location.pathname.replace(/\/$/,'')+'/admin.html';return}const menu=$('menuBtn');if(menu)menu.onclick=()=>$('nav').classList.toggle('open');document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>$('nav').classList.remove('open')));const lf=$('leadForm');if(lf){lf.action=API_URL;lf.addEventListener('submit',()=>setTimeout(()=>{const m=$('formMsg');if(m)m.textContent='Thank you. Your enquiry has been submitted.'},500))}jsonp('public').then(render).catch(e=>{$('loader').innerHTML='<div class="loader-mark">V</div><div style="max-width:310px;line-height:1.5">Website setup is almost ready.<br>'+esc(e.message)+'</div>'})}document.addEventListener('DOMContentLoaded',init);
